force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Represents a trade in which money in a currency was used to buy money in a different currency.</description>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Currency in which the money was bought.</description>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Rate at which the transaction occurred (sell x rate = buy).</description>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Amount of money that was sold in the sell currency.</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Currency in which the money was sold.</description>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>MXN</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>RUB</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>TRY</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>TWD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>THB</fullName>
    </customValue>
    <customValue>
        <fullName>IDR</fullName>
    </customValue>
    <customValue>
        <fullName>HUF</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <customValue>
        <fullName>PHP</fullName>
    </customValue>
    <description>All currencies in which trades can be done.</description>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewTradeController.cls
public with sharing class NewTradeController {

    static final String API_KEY = 'fdd04ab87e325b19ae36c2eaa989abe0';

    public class FixerResponse {
        public Boolean success;
        public Datetime timestamp;
        public String base;
        public Date rateDate;
        public Map<String, Decimal> rates;
    }

    @AuraEnabled
    public static Id insertTrade(String buyCurrency, String sellCurrency, Decimal rate, Decimal sellAmount) { 
        Trade__c trade = new Trade__c(
            Buy_Currency__c = buyCurrency,
            Sell_Currency__c = sellCurrency,
            Rate__c = rate,
            Sell_Amount__c = sellAmount
        );
        insert trade;
        return trade.Id;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Decimal> getRates() {
        FixerResponse fixerResponse = new FixerResponse();

        HttpRequest req = new HttpRequest();
        req.setEndpoint('http://data.fixer.io/api/latest?access_key='+API_KEY);
        req.setMethod('GET');

        HTTPResponse response = new Http().send(req);
        if (response.getStatus() != 'OK')
            throw new AuraHandledException('Could not connect to Fixer.io exchange rate service, please try again later.');
        
        JSONParser parser = JSON.createParser(response.getBody());
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME) {
                switch on parser.getText() {
                    when 'success' {
                        parser.nextToken();
                        fixerResponse.success = parser.getBooleanValue();
                    }
                    when 'timestamp' {
                        parser.nextToken();
                        fixerResponse.timestamp = Datetime.newInstance(parser.getLongValue());
                    }
                    when 'base' {
                        parser.nextToken();
                        fixerResponse.base = parser.getText();
                    }
                    when 'rates' {
                        parser.nextToken();
                        fixerResponse.rates = new Map<String, Decimal>();
                        while (parser.nextToken() != JSONToken.END_OBJECT) {
                            if (parser.getCurrentToken() == JSONToken.FIELD_NAME) {
                                String curr = parser.getText();
                                parser.nextToken();
                                fixerResponse.rates.put(curr, parser.getDecimalValue());
                            }
                        }
                        parser.nextToken();
                    }
                }
            }
        }

        if (!fixerResponse.success || fixerResponse.rates == null)
            throw new AuraHandledException('Could not pull exchange rate from Fixer.io, please try again later.');

        return fixerResponse.rates;
    }
}