force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Represents a trade in which money in a currency was used to buy money in a different currency.</description>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Amount of money that was bought in the buy currency after applying the rate.</description>
    <formula>Sell_Amount__c * Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Currency in which the money was bought.</description>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <description>Date in which this trade happened.</description>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Rate at which the transaction occurred (sell x rate = buy).</description>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Amount of money that was sold in the sell currency.</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Currency in which the money was sold.</description>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>MXN</fullName>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>RUB</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>TRY</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>TWD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>THB</fullName>
    </customValue>
    <customValue>
        <fullName>IDR</fullName>
    </customValue>
    <customValue>
        <fullName>HUF</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>ILS</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <customValue>
        <fullName>PHP</fullName>
    </customValue>
    <description>All currencies in which trades can be done.</description>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradeTriggerHandler.cls
public with sharing class TradeTriggerHandler {

    private Boolean shouldExecute;
    private String chatterGroupName = 'Trade reviewers';

    public TradeTriggerHandler(Boolean isAfter, Boolean isInsert) {
        this.shouldExecute = isAfter && isInsert;
    }

    public void execute(Trade__c[] trades) {
        if (!shouldExecute) return;

        Id collaborationGroupId;
        try {
            collaborationGroupId = [SELECT Id FROM CollaborationGroup WHERE Name =: chatterGroupName LIMIT 1].Id;
        } catch(exception e) {
            collaborationGroupId = setupCollaborationGroup();
            if (collaborationGroupId == null) return;
        }

        FeedItem[] posts = new FeedItem[]{};
        for (Trade__c trade : trades) {
            posts.add(new FeedItem(
                ParentId = collaborationGroupId,
                CreatedById = trade.OwnerId,
                Type = 'TextPost',
                IsRichText = true,
                Body = '<p>A new trade has been created with the following data:</p>'+
                    '<ul>'+
                    '<li>Sell Currency: '+trade.Sell_Currency__c+'</li>'+
                    '<li>Sell Amount: '+trade.Sell_Amount__c+'</li>'+
                    '<li>Buy Currency: '+trade.Buy_Currency__c+'</li>'+
                    '<li>Buy Amount: '+trade.Buy_Amount__c+'</li>'+
                    '<li>Rate: '+trade.Rate__c+'</li>'+
                    '<li>Booked Date: '+trade.Date_Booked__c+'</li>'+
                    '<li>Link to the trade: <a href="'+URL.getOrgDomainUrl().toExternalForm()+'/'+trade.Id+'">'+trade.Name+'</a></li>'+
                    '</ul>'
            ));
        }

        // No need to check for empty list since it will always contain at least 1 record.
        insert posts;
    }

    // This assumes an admin will keep the group updated after it's created.
    public Id setupCollaborationGroup() {
        Id r;
        try {
            CollaborationGroup collaborationGroup = new CollaborationGroup(Name = chatterGroupName, CollaborationType = 'Private');
            insert collaborationGroup;
            r = collaborationGroup.Id;
        } catch (exception e) {}
        return r;
    }
}